### ISSUE TITLE
Changing how URL works 

### ISSUE THREAD

**Issue by gbinal** [WhiteHouse/fitara#14]
Any thoughts on having `management.cio.gov` serve as an alias and not a redirect for `whitehouse.github.io/fitara/`?  Along the same lines as `playbook.cio.gov` and `project-open-data.cio.gov`.

**Comment by jlberryhill** [comment]
Definitely preferable to me. Can we make this work, @treymkennedy?

**Comment by treymkennedy** [comment]
Let me loop in Boris on this and we'll find out what kind of lift this would be from MAX and see if we can do it.

**Comment by gbinal** [comment]
I have a pull request to add in the `CNAME` file - https://github.com/WhiteHouse/fitara/pull/15

**Comment by borisbys** [comment]
@gbinal just asked someone from MAX to accept #15.. not sure if they are on git.

**Comment by borisbys** [comment]
@gbinal @jlberryhill @treymkennedy all done, thanks guys!
