### ISSUE TITLE
Attachment E: fix outline formatting

### ISSUE THREAD

**Issue by bsweezy** [WhiteHouse/fitara#16]
For some reason the outline in Attachment E is appearing all on one line. It should look more like:

Management 
- Program/Project Management 
- Portfolio Management 
- Enterprise 
- Strategy 
- Financial Management

**Comment by gbinal** [comment]
When you see that, it can usually be resolved by adding two spaces to the end of each line.  I did that (and changed over to *-based bullet points) with #17.

**Comment by jlberryhill** [comment]
Actually, don't think that did the trick, @gbinal and @bsweezy.

**Comment by gbinal** [comment]
This issue appears to be resolved, since they aren't all on one line any more (screenshot below).  

The styling isn't what I was going for, hence #18.  

![screen shot 2015-05-04 at 2 03 40 pm](https://cloud.githubusercontent.com/assets/633088/7458952/877398a0-f266-11e4-9ffd-9da1769b76b4.png)

**Comment by gbinal** [comment]
I believe we can close this issue, but let me know if I'm missing something.
