### ISSUE TITLE
Inspector General Independence

### ISSUE THREAD

**Issue by SIGTARP-1** [WhiteHouse/fitara#23]
The Inspector General Act of 1978, as amended, contains a variety of statutory guarantees of Office of Inspector General (OIG) independence, designed to ensure the objectivity of OIG work and to safeguard against efforts to compromise that objectivity or hinder OIG operations.  The feedback below relates to the issue of OIG independence for OMB's consideration.  

First, we want to express appreciation for OMB’s inclusion of language recognizing OIG independence in the Scope and Applicability section.  We recommend that any reference to the Inspector General Act refer to it as the “Inspector General Act of 1978, as amended.” 

The guidance makes clear at the outset of Attachment A that “[a]ll references to ‘CIO’ refer to department/headquarters CIOs, and only references to ‘bureau CIO’ refer to the CIO or official-with-CIO duties within a bureau or any component organization of the agency.”  We have some concern that the agency CIO would have the ability to control the appointment of the CIO of any component organization within the agency, including an OIG.  We believe that such a requirement could impact the independence of the OIGs.  See Section Attachment A - M1 (“The CIO shall be involved in the recruitment and shall approve the selection of any new bureau CIO (includes bureau leadership with CIO duties but not title …”).  

We also wanted to highlight other provisions in Attachment A that appear to allow the agency CIO to have direct and significant authority of the IT functions of an OIG: 

•         C1:  (“The CIO shall be included in the internal planning processes for how the agency uses IT resources to achieve its objectives.  The CIO shall approve the IT components of any plans … This includes CIO involvement with planning for IT resources at all points in their lifecycle …”).  
•         D1: (“CIO reviews and approves major IT investment portion of budget request.  Agency budget justification materials in their initial budget submission to OMB shall include a statement that affirms: the CIO has reviewed and approves the major IT investments portion of this budget request …”
•         G1: (“The CIO defines the development processes, milestones, review gates, and the overall policies for all capital planning and project management and reporting for IT resources.”).  
•         J1:  (“The CIO shall conduct TechStat reviews or use other applicable performance measurements to evaluate the use of the IT resources of the agency.  The CIO may recommend to the agency head the modification, pause, or termination of any acquisition, investment, or activity that includes a significant IT component based on the CIO’s evaluation, within the terms of the relevant contracts and applicable regulations.”).
•         K1: (“Agencies shall not approve an acquisition strategy or acquisition plan … or interagency agreement …. that includes IT without review and approval by the agency CIO.”).
•         N1: (“The [Chief Human Capital Officer](CHCO) and CIO shall jointly establish an agency-wide critical element (or elements) included in all bureau CIOs’ performance evaluations.”).

B. Chad Bungard
General Counsel
Office of the Special Inspector General for the Troubled Asset Relief Program

**Comment by bsweezy** [comment]
Thank you @SIGTARP-1 for your comments. To help clarify how to apply these requirements to the Inspector-General community, the final memorandum includes your recommended language regarding the IG Act. It refers to the “Inspector General Act of 1978, as amended.” In full, that requirement now reads: "With respect to Offices of Inspectors General (OIG), this guidance should be implemented in a manner that does not impact the independence of those offices and the authorities Inspectors General have over the personnel, performance, procurement, and budget of the OIG, as provided in the Inspector General Act of 1978, as amended (5 U.S.C. App 3)."
