### ISSUE TITLE
FITARA for Digital Ae

### ISSUE THREAD

**Issue by timganguly** [WhiteHouse/fitara#24]
The OPM's newer guidance on CIOs are not enough for this ever changing world.

In reality, the future role of CIOs (including CXOs) must be aligned with the Silicon Valley's culture tied to INNOVATION and ACCOUNTABILITY.

In INNOVATION field - the emerging ole of software is becoming predominant, here the software will take the center stage (aka Core competency).  This software in the driving seat will control hardware integration (not like Intel dominance days) as well as Internet of Everything (IoE) movements. This Innovation is fueled by software process improvement through automation (aka adopting to "DevOps" culture). At least after 75 years, the dream of Prof. Deming and Prof. Juran is becoming a reality.

In ACCOUNTABILITY field every CIO must be responsible for his/her own failure. As noted by every GAO reports, there was no accountability in the government compared to the commercial side.

Hopefully, the golden days of Acquisition (based on recent advances in Technology and Logistics) is coming in the government sector based on the new FITARA initiatives from the OPM.

**Comment by bsweezy** [comment]
Thank you @timganguly for your comments. The final memorandum includes specific requirements related to development and operations, such as defining adequate incremental development with an aggressive six month window and ensuring decisions about the ongoing operation and disposition of IT systems is clearly a part of the scope of CIOs' roles. The guidance also requires agencies to increase the accountability of the IT decisionmakers by publishing publicly a Bureau IT Leadership Directory and strengthening the relationship between agency CIOs and bureau CIOs.
