### ISSUE TITLE
Need for IT Spend Visibility Pathfinder Pilot(s)

### ISSUE THREAD

**Issue by rdamashek** [WhiteHouse/fitara#25]
The biggest gap in the draft guidance is the lack of any real guidance on how to effectively implement IT spend visibility across the Planning, Programming, Budgeting and Execution (PPBE) life cycle. In the Common Baseline, the authority is given to the:
1. CFO and CIO to jointly define the level of detail with which IT resource levels are described
2. CFO, CAO and CIO to define agency-wide policy for the level of detail of planned expenditure reporting for all transactions that include IT resources

Achieving effective visibility is a dauntingly difficult challenge. One need only try to fuse the data reported through OMB's IT Dashboard (investment planning/programming) to that reported through sites like USASpending.gov (procurement transactions linked to budgeting/execution) to see the tremendous gap in granularity that needs to be closed to be able to trace investments, let alone performance/results of those investments for the American public, through the PPBE life cycle.  All agencies have to execute essentially the same life cycle, even though some may do it with widely different ways of distributing organizational authority and management due to the nature and culture of their agency. With the current guidance, the Federal government is almost guaranteed to achieve almost as many different variations in IT spend visibility success as there are agencies.

What is sorely missing from the guidance is an explicit requirement for establishing and executing one or more Pathfinder pilots to determine and converge on effective and common mechanisms to trace IT spend through the PPBE cycle to results and outcomes for agency missions.  One way to establish this requirement could be by adding an action to the end of Section B for OMB to initiate its own pilot, potentially through the US Digital Service, and establish timelines for reporting the results through the CIO Council in its quarterly meetings.  Another, or perhaps additional approach might be to require each agency CIO to initiate their own such pilot in Sections A1 and E1 of the Common Baseline, similarly establish timelines for reporting the results either to the CIO Council or to OMB directly, and converge best practices from those results to establish Government-wide standards for implementing IT spend visibility.

Making these changes to the guidance will actually give agencies a chance to successfully and more rapidly achieve the goals for more effective and efficient Government that Congress envisioned when crafting the FITARA legislation.  As a note, though elements of the DATA act might be leveraged, the act is focused on achieving greater investment transparency at the award level, and not throughout the PPBE life cycle in a traceable and consistent manner.

Robert Damashek
CTO, Binary Group

**Comment by bsweezy** [comment]
Thank you @rdamashek for your comments. One of the reasons OMB established "https://management.cio.gov" as a place to discuss this proposed guidance was to ensure that there is also a place to share tools, resources, and status updates on the details of agencies' implementation of this guidance. The types of challenges you identify in your comment are a part of the work agencies will be tackling as they develop their Self-Assessments and Implementation Plans to make the requirements of this memorandum a reality in their environments.
