### ISSUE TITLE
Treasury OPE Comments on OMB FITARA Guidance

### ISSUE THREAD

**Issue by jeff-bishop** [WhiteHouse/fitara#26]
These comments focus on the portions of OMB’s guidance related directly to the CIO’s and CAO’s respective roles in the acquisition process as defined in the Common Baseline, as well as general acquisition guidance in Section E.  

Section E Comments:

Section E, Paragraph 1: This paragraph references Attachment F.  The guidance posted on GitHub does not contain Attachment F.  Regarding IT Acquisition Cadres, Treasury feels it is vital for these cadres to include Contracting Officers (COs) and Contracting Officer Representatives (CORs), and that COs and CORs must be trained together, instead of training occurring in separate CO and COR tracks.

Section E, Paragraph 2: Will there be any oversight or tracking of agency contract actions that do not utilize FSSI vehicles?  Without oversight or some reporting mechanism, it will be very difficult to identify which FSSI vehicles agencies aren’t using, and their rationale behind not using them.   

Section E, Paragraph 3: Will the new GSA Software Category Management team replace, absorb, or work with DoD’s Enterprise Software Initiative (ESI) to reduce duplicative software license/maintenance contracts?  OMB’s guidance states the Category Management Initiative will result in license agreements available for use by all executive agencies, however, DoD’s ESI has many contract vehicles civilian agencies are unable to utilize (e.g., Adobe, Microsoft, Red Hat).  The software spend won’t truly be leveraged across government until DoD ESI and GSA ensure all vehicles awarded by either are available for all agencies to order against.

Attachment A Comments:
Paragraph K1: While Treasury agrees it is vital to have customer buy-in (up to and including the agency CIO for major acquisitions) on the acquisition strategy/plan, there is some concern that this usurps the contracting officer’s (CO) authority and/or has the potential to result in undue pressure being put on a contracting officer from an agency CIO in the event the agency CIO does not concur with the CO’s proposed acquisition strategy/plan. 
Paragraph K2: Why is OMB requiring the CAO to notify the CIO when a planned acquisition includes IT?  The agency CIO should institute policy to determine how IT-related requirements are identified and submitted to contracting.

Paragraph K2: “Substantial changes to the scope of a significant contract” is a very vague term.  Recommend simply stating the language to simply state “CAO shall ensure no out of scope contract changes…”  Also recommend defining the term “significant” contract.

**Comment by bsweezy** [comment]
Thank you @jeff-bishop for your comments. The final memorandum clarifies that agencies will describe their approach to IT acquisition cadres in consistent reports to OMB. OMB is working with the FAR Council to ensure that the kind of reporting you recommend is included when purchases do not use FSSI vehicles, as required by FITARA. Finally, DOD is a member of the IT Category Management team led by OMB and GSA to establish government-wide licenses.
