### ISSUE TITLE
130 micro-purchase approvals per hour!

### ISSUE THREAD

**Issue by arlotti-parish** [WhiteHouse/fitara#31]
The average agency CIO would need to approve 130 charge card transactions every hour\* to meet the review and approval requirements in sections I1 and K1.  These micro-purchases average $309 per transaction.  Similarly new ODCs that are purchased as part of an existing contract could similarly flood the IT executives in overwhelming minutiae.  Your guidance should make it clear that approval authority for these charge card and ODC purchases on an approved contract, can be delegated down to far lower levels in the organization as long as they fall under a parent contract that has been approved by the CIO.  
- GSA reports 85M SmartPay card transactions per year \* 6.8% (average fraction of budget spent on IT) / 24 CFO Act Agencies / 1920 hours per year = 130 card transactions per agency per hour.  https://www.smartpay.gsa.gov/about-gsa-smartpay/program-statistics

**Comment by bsweezy** [comment]
Thank you @arlotti-parish for your comments. Please see question #4 in the FAQs on https://management.cio.gov: "Won’t this make today’s CIOs a bottleneck and damage agencies’ ability to deliver their programs?" Through extensive outreach and collaboration, we believe we have developed a memorandum that is applicable to all agencies in a way that gives them flexibility to implement the law’s requirements and does not create unnecessary bottlenecks. This was an initial primary concern of many CIOs and agency executives. In response, we created the CIO Assignment Plan to allow the CIO to assign, in a rules-based manner, certain responsibilities to other people in their department. This keeps the accountability with the CIO but allows each agency to realistically meet the law’s requirements while minimizing the chance for bottlenecks.
