### ISSUE TITLE
FITARA:Section 831 conflicts with Independence section of HEA legislation

### ISSUE THREAD

**Issue by JayHurt** [WhiteHouse/fitara#33]
FITARA has seven separate sections (sections 831-837).  Federal Student Aid’s (FSA) Performance-Based Organization (PBO) legislation and FITARA seem to have conflicting requirements with one of the seven sections (Section 831).  Specifically, in FSA’s PBO legislation (i.e., the Higher Education Act), there is a clause (Section 141(b)(4)) about independence:

(4) Independence – Subject to paragraph (1), in carrying out its functions, the PBO shall exercise independent control of its budget allocations and expenditures, personnel decisions and processes, procurements, and other administrative and management functions.

The recently enacted Federal Information Technology Acquisition Reform Act (FITARA) has the following four clauses in Section 831 (Chief Information Officer Authority Enhancements) that seem to conflict with this clause and the general intention of the PBO legislation.

‘‘(i) That the Chief Information Officer of each covered agency other than the Department of Defense approve the information technology budget request of the covered agency,”

‘‘(ii) That the Chief Information Officer of each covered agency certify that information technology investments are adequately implementing incremental development, as defined in capital planning guidance issued by the Office of Management and Budget.

‘‘(C) REVIEW.—(i) IN GENERAL.—A covered agency other than the Department of Defense—
‘(I) may not enter into a contract or other agreement for information technology or information technology services, unless the contract or other agreement has been reviewed and approved by the Chief Information Officer of the agency;
‘(II) may not request the reprogramming of any funds made available for information technology programs, unless the request has been reviewed and approved by the Chief Information Officer of the agency;

‘‘(2) PERSONNEL-RELATED AUTHORITY.—Notwithstanding any other provision of law, for each covered agency other than the Department of Defense, the Chief Information Officer of the covered agency shall approve the appointment of any other employee with the title of Chief Information Officer, or who functions in the capacity of a Chief Information Officer, for any component organization within the covered agency.

Requiring the Department of Education’s CIO to approve FSA’s IT budget allocation and expenditures, IT personnel decisions, and IT procurements seems to be in direct conflict with the language and intent of FSA's PBO legislation.  I believe there are strong arguments to support a determination that the FITARA guidance should be implemented in a manner that does not impact the independence and authority of FSA with regard to personnel, performance, procurement, and budget, as provided in the Higher Education Act, 20 U.S.C. § 1018(b)(4).  I would welcome further coordinated discussions amongst PBOs (and similarly situated agency bureaus with independent authority of their management and procurement), their agencies, and OMB.

**Comment by bsweezy** [comment]
Thank you @JayHurt for your comments. Each agency should ensure that their implementation of FITARA is consistent with the statutory environment they in which they operate. Please see #3 in the "scope and applicability" section of the memorandum. Please note, however, that the FITARA law uses the following language regarding bureau CIOs:

"Notwithstanding any other provision of law, for each covered agency … the Chief Information Officer of the covered agency shall approve the appointment of any other employee with the title of Chief Information Officer, or who functions in the capacity of a Chief Information Officer, for any component organization within the covered agency."
